### ISSUE TITLE
Client API?

### ISSUE THREAD

**Issue by pwFoo** [landrok/activitypub#1]
Hi,

looks like a client api is planned, but not ready?
And which clients should be compatible to the client api (mastodon web client, mastodon apps)?

**Comment by landrok** [comment]
Hi,
absolutely, it's planned but not yet implemented.
Currently, the server part is in active development.
Beforehand, there is also the implementation of different dialects (Mastodon, peertube and pixelfed) to facilitate integrations with some common ActivityPub dialects.
There will be (as) soon (as possible) a push for this new feature.
