### ISSUE TITLE
Signature pattern failed with Mastodon/Pleroma requests

### ISSUE THREAD

**Issue by GuDzpoz** [landrok/activitypub#16]
The signature field in the request was `keyId="https://domain/path#main-key",algorithm="rsa-sha256",headers="(request-target) host date digest content-type",signature="zRbQw......0MUqA=="`, and I suspect that the *algorithm="rsa-sha256"* field has caused this problem. (By the way, requests from both Mastodon and Pleroma seem to be using rsa-sha256.) 

Can this be fixed somehow? Thanks!

**Comment by landrok** [comment]
Hi, you're true, the algorithm field is not matched by the extraction pattern.

A patch has been applied and packaged with the 0.5.3 release. Can you test it and tell me if it works with your use-case ?

**Comment by GuDzpoz** [comment]
The pattern matching still went wrong, but after some testing it seems that it is another issue other than the algorithm field, which has been resolve by your patch. 
I've opened pull request #17 and the modification works for me. Would you please check it out?

**Comment by landrok** [comment]
Packaged with the 0.5.4 release

Thanks 👍
