### ISSUE TITLE
Use webfinger for public key and client side signing

### ISSUE THREAD

**Issue by pwFoo** [landrok/activitypub#2]
Hi,
I start to play with webfinger and webrtc and would like to use your ActivityPub library because my small project could be extended with activitypub features later...
So I know it's a little bit of topic, but I hope you could help me to be compatible with your project 😅

Two questions about how to use it.

1) It looks like webfinger would be nice to store a public key used for signature verification and optional encryption.
Is it possible to add a public key to the webfinger user "file" and is it possible to get that attribute with your webfinger implementation?

2) Content should be signed / encrypted client side. So how to do it with JavaScript to be compatible to `HttpSignature::verify()`?
Client side encryption library examples:
- https://github.com/intelliBrain/cryptico-js
- https://github.com/travist/jsencrypt

**Comment by pwFoo** [comment]
So I'm interested in the `$request` value and how to send it. Looks like a http header to send with the request, but I have no symfony instance of
`Symfony\Component\HttpFoundation\Request` from client.

**Comment by landrok** [comment]
__Is it possible to add a public key to the webfinger user "file" and is it possible to get that attribute with your webfinger implementation?__


```php
use ActivityPhp\Server;

$handle = 'username@example.com';

$server = new Server();

// Build a server-oriented actor
$actor = $server->actor($handle);

// Get public key
$publicKeyPem = $actor->getPublicKeyPem();
```

The public key is bound to the actor (not to the webfinger profile).
It's not part of ActivityPub protocol but a common practice.

[Some links in the footer](https://landrok.github.io/activitypub/activitypub-server-verify-http-signatures.html#activitypub-conformance)


__Content should be signed / encrypted client side. So how to do it with JavaScript to be compatible to HttpSignature::verify()?__

`HttpSignature::verify()` is a server-to-server verification.
It [sends a request](https://landrok.github.io/activitypub/activitypub-server-verify-http-signatures.html#httpsignatureverify) to distant host to discover user's profile (WebFinger) and load Actor's profile (with the public key). 

I don't know these JS libraries but at first glance, an embedded client (into browser) should not work with HTTP signature verification.
I think it's useful for end-to-end encryption.


__About $request__

Sending requests is not yet fully implemented. I will make a manual as soon as it works.


Thank you for your questions.

**Comment by pwFoo** [comment]
What I try to do is client generated private / public key used to sign requests to the server and verify with public key, which is uploaded from client and should be available on the server / webfinger profile.
That signing und request part isn't activitypub protocol, but if possible I would try to reuse the tools of your library.
