### ISSUE TITLE
How to use this as a federated server?

### ISSUE THREAD

**Issue by RikudouSage** [landrok/activitypub#37]
What I want to do is create a server that will be federated with Lemmy instances and will receive pings to the inbox like Lemmy instances do. I can't find any documentation about anything similar. Is it supported? If so, how?

**Comment by mediaformat** [comment]
@RikudouSage you have to define routes yourself, for the actor, inbox, outbox.

You can use this lib to verify http signatures of incoming requests. But saving/storing is entirely up to you.

**Comment by RikudouSage** [comment]
I've opted for a different way of solving my problem.
