### ISSUE TITLE
0.4.0 release?

### ISSUE THREAD

**Issue by swentel** [landrok/activitypub#6]
Hi,

I'm (finally) working on ActivityPub for Drupal using your library, and it's coming along well.

I was wondering whether you have an ETA to tag a new release? That would allow me to set a stable tag in my composer file, instead of having to rely on dev/master branch.

Thanks!

**Comment by landrok** [comment]
Hi Kristof,

Good news :)

[0.4.0](https://github.com/landrok/activitypub/releases/tag/0.4.0) has just been released as stable tag.

Thanks you for using ActivityPhp.

**Comment by swentel** [comment]
Woohoow, thanks!

I'll ping you from my site account once I get it all up and running, might take a few more weeks though, but it will be cool :)
