### ISSUE TITLE
Use some sort of cache in WebfingerFactory

### ISSUE THREAD

**Issue by swentel** [landrok/activitypub#7]
When using following code:

```
$webfinger = $server->actor($handle)->webfinger();
```

The call to the webfinger url happens twice 

- first in __construct of Actor.php
- then in webfinger()

There's a property webfingers, but a quick debug by adding in the get() method of the factory doesn't help, because well, it's static (unless I miss something very stupid here).

Not sure what the most elegant way would be to handle it.

**Comment by swentel** [comment]
Now that I think of it, this is probably because I disabled caching in my server object. Since I'm using this in Drupal, I have a bunch of other caching at my disposal. Still, might be useful to get around this I think.

**Comment by landrok** [comment]
I've pushed some new ways to [handle cache](https://landrok.github.io/activitypub/activitypub-server-usage.html#cache-parameters), especially for supporting frameworks cache pools.

Custom cache pools need to implement PSR-6.

I hope it helps you for Drupal integration.

Let me know if you have some additional questions.
