### ISSUE TITLE
Signature pattern too strict

### ISSUE THREAD

**Issue by swentel** [landrok/activitypub#9]
The signature pattern is quite strict on the padding signs at the end. I'm getting signatures now and then with one or sometimes without equal signs in the end. So something like underneath makes the preg match work fine. Unless there's a requirement for having two there, but I don't think so :)

```
/^
        keyId="(?P<keyId>
            (https?:\/\/[\w\-\.]+[\w]+)
            (:[\d]+)?
            ([\w\-\.#\/@]+)
        )",
        (headers="\(request-target\) (?P<headers>[\w\s]+)",)?
        signature="(?P<signature>[\w+\/]+={0,2})"
    /x
```

**Comment by landrok** [comment]
LGTM
Thanks :)
